# Generated by Django 5.2 on 2026-07-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_passenger'),
        ('flights', '0004_airport_terminals'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='flights.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flightinstance'),
        ),
    ]
