# Generated by Django 5.2 on 2026-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cabin_class',
            field=models.CharField(blank=True, choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10, null=True),
        ),
    ]
