# Generated by Django 5.2 on 2026-08-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_seat_number_to_passenger'),
        ('flights', '0008_add_delay_minutes_to_flight_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flightinstance'),
        ),
    ]
