# Generated by Django 5.2 on 2026-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_passengermeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='meal_preference',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('NONE', 'No Preference')], default='NONE', help_text='Complimentary in-flight meal preference', max_length=10),
        ),
    ]
