# Generated by Django 5.2 on 2026-08-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_passenger_meal_preference'),
        ('flights', '0016_flightmeal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.flightinstance'),
        ),
    ]
