# Generated by Django 5.2 on 2026-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='extra_baggage_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for extra baggage in booking currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='passenger',
            name='extra_baggage_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchased extra baggage in kg', max_digits=6),
        ),
    ]
