# Generated by Django 5.2 on 2026-08-13 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_passenger_extra_baggage_cost_and_more'),
        ('flights', '0017_flightroute_extra_baggage_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='flights.flightinstance')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='flights.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at'],
            },
        ),
    ]
