# Generated by Django 5.2 on 2026-08-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_add_seat_hold_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='free_baggage_allowance_kg',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Snapshot of free checked baggage allowance in kg at booking time', max_digits=6),
        ),
        migrations.AddField(
            model_name='passenger',
            name='free_handbag_allowance_kg',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Snapshot of free handbag allowance in kg at booking time', max_digits=6),
        ),
    ]
