# Generated by Django 5.2 on 2026-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_passenger_free_baggage_allowance_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='free_baggage_allowance_kg',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Snapshot of free checked baggage allowance at booking time', max_digits=6),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='free_handbag_allowance_kg',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Snapshot of free handbag allowance at booking time', max_digits=6),
        ),
    ]
