# Generated by Django 5.2 on 2026-08-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_passenger_free_baggage_allowance_kg_and_more'),
        ('flights', '0020_flightroute_is_active_flightroute_operates_on_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('fare_code', models.CharField(max_length=20)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('refund_type', models.CharField(choices=[('REFUNDABLE', 'Refundable'), ('NON_REFUNDABLE', 'Non-Refundable'), ('PARTIAL', 'Partial')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='flights.fare')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='flights.flightinstance')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='flights.seat')),
            ],
            options={
                'ordering': ['booking', 'created_at'],
            },
        ),
    ]
