# Generated by Django 5.2 on 2026-07-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('waitlist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='waitlist.waitlistentry')),
            ],
        ),
    ]
