# Generated by Django 5.2 on 2026-07-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('WAITLIST_ALLOCATED', 'Waitlist Allocated'), ('FLIGHT_DELAYED', 'Flight Delayed'), ('FLIGHT_CANCELLED', 'Flight Cancelled'), ('FLIGHT_BOARDING', 'Flight Boarding'), ('FLIGHT_DEPARTED', 'Flight Departed'), ('FLIGHT_ARRIVED', 'Flight Arrived')], max_length=50),
        ),
    ]
