# Generated by Django 5.0 on 2026-07-10 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('aircraft', models.CharField(max_length=100)),
                ('source_airport', models.CharField(max_length=10)),
                ('destination_airport', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived')], default='SCHEDULED', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('sync_source', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('available_seats__gte', 0)), name='available_seats_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('total_seats__gte', 0)), name='total_seats_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('arrival_time__gt', models.F('departure_time'))), name='arrival_time_after_departure_time'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('source_airport', models.F('destination_airport')), _negated=True), name='source_dest_not_equal'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('base_fare__gte', 0)), name='base_fare_non_negative'),
        ),
    ]
