# Generated by Django 5.2 on 2026-07-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_airline_code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('airline_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['airline_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(db_index=True, max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(db_index=True, max_length=20, unique=True)),
                ('economy_capacity', models.PositiveIntegerField(default=0)),
                ('business_capacity', models.PositiveIntegerField(default=0)),
                ('first_class_capacity', models.PositiveIntegerField(default=0)),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='flights.aircraftmodel')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='flights.airline')),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('airport_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='flights.country')),
            ],
            options={
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived')], default='SCHEDULED', max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('checkin_open', models.DateTimeField(blank=True, null=True)),
                ('boarding_time', models.DateTimeField(blank=True, null=True)),
                ('boarding_gate', models.CharField(blank=True, default='', max_length=10)),
                ('departure_terminal', models.CharField(blank=True, default='', max_length=10)),
                ('arrival_terminal', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='flights.aircraft')),
            ],
            options={
                'ordering': ['-date', 'flight'],
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_code', models.CharField(max_length=20)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('available_seats', models.IntegerField(default=0)),
                ('refund_type', models.CharField(choices=[('REFUNDABLE', 'Refundable'), ('NON_REFUNDABLE', 'Non-Refundable'), ('PARTIAL', 'Partial')], default='NON_REFUNDABLE', max_length=20)),
                ('change_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meal_included', models.BooleanField(default=False)),
                ('baggage_allowance', models.DecimalField(blank=True, decimal_places=2, help_text='Override flight-level baggage allowance (kg). Leave blank to use flight default.', max_digits=6, null=True)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='flights.flightinstance')),
            ],
            options={
                'ordering': ['flight_instance', 'cabin_class', 'price'],
            },
        ),
        migrations.CreateModel(
            name='FlightMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='flights.flightinstance')),
            ],
            options={
                'ordering': ['flight_instance', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('baggage_weight_allowed_per_person', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('baggage_number_allowed_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('handbag_weight_allowed_per_person', models.DecimalField(decimal_places=2, default=7, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_routes', to='flights.airline')),
            ],
            options={
                'ordering': ['flight_no'],
            },
        ),
        migrations.AddField(
            model_name='flightinstance',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='flights.flightroute'),
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_items/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='flights.airline')),
            ],
            options={
                'ordering': ['airline', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_order', models.PositiveIntegerField()),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_legs', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_legs', to='flights.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flightroute')),
            ],
            options={
                'ordering': ['flight', 'leg_order'],
                'unique_together': {('flight', 'leg_order')},
            },
        ),
        migrations.CreateModel(
            name='FlightMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('flight_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flights.flightmeal')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='flights.fooditem')),
            ],
            options={
                'ordering': ['flight_meal', 'food_item'],
                'unique_together': {('flight_meal', 'food_item')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('seat_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('position', models.CharField(blank=True, choices=[('window', 'Window'), ('aisle', 'Aisle'), ('middle', 'Middle')], default='', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=10)),
                ('exit_row', models.BooleanField(default=False)),
                ('seat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flightinstance')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('flight_instance', 'seat_number')},
            },
        ),
    ]
