# Generated by Django 5.2 on 2026-07-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airline_country_aircraftmodel_aircraft_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='terminals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
