# Generated by Django 5.2 on 2026-07-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airport_terminals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name_plural': 'Countries'},
        ),
    ]
