# Generated by Django 5.2 on 2026-07-31 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='extra_legroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_rule_applied',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='SeatPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rules', models.JSONField(default=list, help_text='List of {"attribute": "window"|"aisle"|"middle"|"exit_row"|"extra_legroom", "price": <number>} dicts ordered by priority (last wins on conflict).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_price_templates', to='flights.aircraftmodel')),
            ],
            options={
                'ordering': ['aircraft_model', 'name'],
                'unique_together': {('aircraft_model', 'name')},
            },
        ),
    ]
