# Generated by Django 5.2 on 2026-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_seat_extra_legroom_last_rule_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='flight_duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Duration of flight leg in minutes'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='layover_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Layover duration before this leg in minutes'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='scheduled_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
