# Generated by Django 5.2 on 2026-08-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_legacy_flight_to_flightinstance'),
        ('flights', '0008_add_delay_minutes_to_flight_instance'),
        ('waitlist', '0004_legacy_flight_to_flightinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
