# Generated by Django 5.2 on 2026-08-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_legacy_flight_to_flightinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='business_layout',
            field=models.CharField(default='2-2', max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='economy_layout',
            field=models.CharField(default='3-3', max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='first_class_layout',
            field=models.CharField(default='2-2', max_length=20),
        ),
    ]
