# Generated by Django 5.2 on 2026-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_aircraft_business_layout_aircraft_economy_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airlines/'),
        ),
    ]
