# Generated by Django 5.2 on 2026-08-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_alter_flightinstance_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmealitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='flights.fooditem'),
        ),
    ]
