# Generated by Django 5.2 on 2026-08-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_flightmealitem_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='flights.aircraftmodel'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='flights.airline'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='flights.aircraft'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_legs', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_legs', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='flights.airline'),
        ),
    ]
