# Generated by Django 5.2 on 2026-08-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_aircraft_aircraft_model_alter_aircraft_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='flights.aircraftmodel'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='flights.airline'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='flights.aircraft'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_legs', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightleg',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_legs', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightmealitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='flights.fooditem'),
        ),
        migrations.AlterField(
            model_name='flightroute',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_routes', to='flights.airline'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='flights.airline'),
        ),
    ]
