# Generated by Django 5.2 on 2026-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_flightmeal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='extra_baggage_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='extra_baggage_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='max_extra_baggage_kg_per_person',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
    ]
