# Generated by Django 5.2 on 2026-08-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_flightroute_extra_baggage_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='baggage_pieces_allowance',
            field=models.PositiveIntegerField(blank=True, help_text='Override flight-level baggage piece count. Leave blank to use flight default.', null=True),
        ),
        migrations.AddField(
            model_name='fare',
            name='handbag_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override flight-level handbag allowance (kg). Leave blank to use flight default.', max_digits=6, null=True),
        ),
    ]
