# Generated by Django 5.2 on 2026-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_fare_baggage_pieces_allowance_fare_handbag_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='baggage_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override flight-level checked baggage allowance (kg). Leave blank to use flight default.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fare',
            name='baggage_pieces_allowance',
            field=models.PositiveIntegerField(blank=True, help_text='Override flight-level free checked piece count. Leave blank to use flight default.', null=True),
        ),
    ]
