# Generated by Django 5.2 on 2026-08-24 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_alter_fare_baggage_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='operates_on_days',
            field=models.CharField(default='1,2,3,4,5,6,7', help_text="Comma-separated ISO weekdays, e.g. '1,2,3,4,5'", max_length=13),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FarePriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='flights.fare')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteFareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('fare_code', models.CharField(max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('refund_type', models.CharField(choices=[('REFUNDABLE', 'Refundable'), ('NON_REFUNDABLE', 'Non-Refundable'), ('PARTIAL', 'Partial')], default='NON_REFUNDABLE', max_length=20)),
                ('change_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meal_included', models.BooleanField(default=False)),
                ('baggage_weight_allowed_kg', models.PositiveIntegerField(default=15)),
                ('extra_baggage_price_per_kg', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_classes', to='flights.flightroute')),
            ],
            options={
                'ordering': ['route', 'cabin_class', 'fare_code'],
                'unique_together': {('route', 'cabin_class', 'fare_code')},
            },
        ),
    ]
