# Generated by Django 5.2 on 2026-08-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_flightroute_is_active_flightroute_operates_on_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farepricechangelog',
            name='route_fare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='flights.routefareclass'),
        ),
        migrations.AlterField(
            model_name='farepricechangelog',
            name='fare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='flights.fare'),
        ),
    ]
