# Generated by Django 5.2 on 2026-08-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_farepricechangelog_route_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='scheduled_arrival_time',
            field=models.TimeField(blank=True, help_text='Leg scheduled arrival time', null=True),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='scheduled_departure_time',
            field=models.TimeField(blank=True, help_text='Leg scheduled departure time', null=True),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='scheduled_arrival_time',
            field=models.TimeField(blank=True, help_text='Daily arrival time of the whole flight', null=True),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='scheduled_departure_time',
            field=models.TimeField(blank=True, help_text='Daily departure time of the whole flight', null=True),
        ),
    ]
