# Generated by Django 5.2 on 2026-08-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_flightleg_scheduled_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Global Dynamic Pricing Settings', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('weekend_surge_enabled', models.BooleanField(default=True)),
                ('weekend_days', models.CharField(default='6,7', help_text='Comma-separated ISO weekdays (6=Saturday, 7=Sunday)', max_length=15)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.15, help_text='e.g. 1.15 = +15% surge', max_digits=5)),
                ('demand_surge_enabled', models.BooleanField(default=True)),
                ('rolling_window_days', models.PositiveIntegerField(default=7, help_text='Lookback window in days for booking count')),
                ('initial_booking_threshold', models.PositiveIntegerField(default=50, help_text='Number of recent bookings to trigger initial surge')),
                ('initial_surge_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Initial surge % at threshold', max_digits=5)),
                ('booking_step_size', models.PositiveIntegerField(default=10, help_text='Additional bookings per incremental step')),
                ('step_surge_percent', models.DecimalField(decimal_places=2, default=2.0, help_text='Additional surge % per step', max_digits=5)),
                ('max_demand_surge_percent', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum allowed demand surge cap %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.2, help_text='e.g. 1.20 = +20% surge', max_digits=5)),
                ('is_global', models.BooleanField(default=False, help_text='If true, applies to all flights globally regardless of region')),
                ('applicable_countries', models.JSONField(blank=True, default=list, help_text="List of country names, e.g. ['India', 'United States']")),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('holiday_applied', models.CharField(blank=True, default='', max_length=100)),
                ('demand_surge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recent_booking_count', models.PositiveIntegerField(default=0)),
                ('final_calculated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_logs', to='flights.fare')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_price_logs', to='flights.flightinstance')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
