# Generated by Django 5.2 on 2026-08-27 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0023_dynamicpricingconfig_holidayevent_dynamicpricelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='weekend_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.15'), help_text='e.g. 1.15 = +15% surge', max_digits=5),
        ),
        migrations.AlterField(
            model_name='holidayevent',
            name='surge_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.20'), help_text='e.g. 1.20 = +20% surge', max_digits=5),
        ),
    ]
