# Generated by Django 5.2 on 2026-09-01 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0025_proximity_occupancy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='price_ceiling_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Maximum combined price as % of base price (e.g. 150 = never above 150% of base)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='price_floor_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Minimum combined price as % of base price (e.g. 80 = never below 80% of base)', max_digits=5),
        ),
        migrations.AlterModelTable(
            name='dynamicpricelog',
            table='flights_dynamicpricelog',
        ),
        migrations.AlterModelTable(
            name='dynamicpricingconfig',
            table='flights_dynamicpricingconfig',
        ),
        migrations.AlterModelTable(
            name='holidayevent',
            table='flights_holidayevent',
        ),
    ]
