# Generated by Django 5.2 on 2026-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0027_redesign_flight_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmeal',
            name='cabin_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=10),
        ),
    ]
