# Generated by Django 5.2 on 2026-09-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0028_alter_flightmeal_cabin_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routefareclass',
            name='extra_baggage_price_per_kg',
        ),
    ]
