# Generated by Django 5.2 on 2026-09-11 05:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0029_remove_extra_baggage_from_routefareclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpricingconfig',
            name='proximity_premium_high_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Max price increase % at departure day when occupancy is 70-84% (standalone tier cap)', max_digits=5),
        ),
        migrations.AddField(
            model_name='dynamicpricingconfig',
            name='proximity_premium_moderate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Max price increase % at departure day when occupancy is 50-69% (standalone tier cap)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='max_proximity_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Max price decrease % at departure day when occupancy is < 30% (standalone tier cap)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='max_proximity_premium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Max price increase % at departure day when occupancy is >= 85% (top tier, standalone — not a fraction of anything)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='occupancy_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Legacy field, no longer read by proximity pricing (tiered logic replaced the single threshold). Kept for backward compatibility.', max_digits=5),
        ),
    ]
