# Generated by Django 5.2 on 2026-09-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0029_remove_extra_baggage_from_routefareclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='aircraft',
            field=models.ForeignKey(blank=True, help_text='Default aircraft for all instances of this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_routes', to='flights.aircraft'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='arrival_terminal',
            field=models.CharField(blank=True, default='', help_text='Default arrival terminal for instances', max_length=10),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='departure_terminal',
            field=models.CharField(blank=True, default='', help_text='Default departure terminal for instances', max_length=10),
        ),
    ]
