# Generated by Django 5.2 on 2026-09-11 06:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0030_dynamicpricingconfig_proximity_premium_high_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpricingconfig',
            name='proximity_ramp_curve_exponent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Shape of the day-based ramp within the proximity window. 1.00 = linear (current default before this field existed). Less than 1.00 front-loads the ramp so most of the effect is reached earlier in the window (e.g. 0.50 = square-root curve). Greater than 1.00 back-loads it so effect stays low until close to departure. Must be greater than 0.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='max_proximity_premium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Max price increase % at departure day when occupancy is >= 85% (top tier, standalone — not a fraction of anything)', max_digits=5),
        ),
    ]
