# Generated by Django 5.2 on 2026-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0030_flightroute_aircraft_flightroute_arrival_terminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightroute',
            name='arrival_terminal',
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='departure_terminal',
        ),
        migrations.AddField(
            model_name='flightleg',
            name='arrival_terminal',
            field=models.CharField(blank=True, default='', help_text='Arrival terminal for this leg', max_length=10),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='departure_terminal',
            field=models.CharField(blank=True, default='', help_text='Departure terminal for this leg', max_length=10),
        ),
    ]
