# Generated by Django 5.2 on 2026-09-11 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0031_dynamicpricingconfig_proximity_ramp_curve_exponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpricingconfig',
            name='max_proximity_premium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Max price increase % at departure day when occupancy is >= 85% (top tier, standalone — not a fraction of anything)', max_digits=5),
        ),
    ]
