# Generated by Django 5.2 on 2026-09-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0031_remove_flightroute_arrival_terminal_and_more'),
        ('flights', '0033_alter_dynamicpricingconfig_max_proximity_discount_percent_and_more'),
    ]

    operations = [
    ]
