# Generated by Django 5.2 on 2026-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistpassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='cabin_class',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=10),
        ),
    ]
