# Generated by Django 5.2 on 2026-07-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airport_terminals'),
        ('waitlist', '0002_waitlistpassenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='flights.flightinstance'),
        ),
    ]
