# Generated by Django 5.2 on 2026-08-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_add_delay_minutes_to_flight_instance'),
        ('waitlist', '0003_waitlistentry_cabin_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='flights.flightinstance'),
        ),
    ]
