# Generated by Django 5.2 on 2026-08-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flightleg_flight_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightinstance',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Delay in minutes (0 = no delay)'),
        ),
    ]
