# Generated by Django 5.2 on 2026-08-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_airline_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinstance',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='flights.flightroute'),
        ),
    ]
