# Generated by Django 5.2 on 2026-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='stops',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
