# Generated by Django 5.2 on 2026-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cabin_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Allocated seat number (e.g. 12A)', max_length=10, null=True),
        ),
    ]
